KREF='/Volumes/BB_HQ_3/Brain_aging_Simons/Misc/Killi_Bulk_Brain/STAR/GCF_001465895.1_MASKED_withFishTEDB_NR'

# # # map with STAR
# STAR --genomeDir $KREF --readFilesIn ../FASTQ_HardTrim/GRZ_F_Brain_c1_O_CTL1_1_val_1.fq.gz   ../FASTQ_HardTrim/GRZ_F_Brain_c1_O_CTL1_2_val_2.fq.gz  --outFilterScoreMinOverLread 0.4 --outFilterMatchNminOverLread 0.4 --readFilesCommand gzcat --runThreadN 1 --outFilterMultimapNmax 50 --outFilterIntronMotifs RemoveNoncanonicalUnannotated --outSAMtype BAM SortedByCoordinate  --alignEndsProtrude 15 ConcordantPair --outFileNamePrefix GRZ_F_Brain_c1_O_CTL_rep1_STAR_  
# STAR --genomeDir $KREF --readFilesIn ../FASTQ_HardTrim/GRZ_F_Brain_c1_O_CTL2_1_val_1.fq.gz   ../FASTQ_HardTrim/GRZ_F_Brain_c1_O_CTL2_2_val_2.fq.gz  --outFilterScoreMinOverLread 0.4 --outFilterMatchNminOverLread 0.4 --readFilesCommand gzcat --runThreadN 1 --outFilterMultimapNmax 50 --outFilterIntronMotifs RemoveNoncanonicalUnannotated --outSAMtype BAM SortedByCoordinate  --alignEndsProtrude 15 ConcordantPair --outFileNamePrefix GRZ_F_Brain_c1_O_CTL_rep2_STAR_  
# STAR --genomeDir $KREF --readFilesIn ../FASTQ_HardTrim/GRZ_F_Brain_c1_O_CTL3_1_val_1.fq.gz   ../FASTQ_HardTrim/GRZ_F_Brain_c1_O_CTL3_2_val_2.fq.gz  --outFilterScoreMinOverLread 0.4 --outFilterMatchNminOverLread 0.4 --readFilesCommand gzcat --runThreadN 1 --outFilterMultimapNmax 50 --outFilterIntronMotifs RemoveNoncanonicalUnannotated --outSAMtype BAM SortedByCoordinate  --alignEndsProtrude 15 ConcordantPair --outFileNamePrefix GRZ_F_Brain_c1_O_CTL_rep3_STAR_  
# STAR --genomeDir $KREF --readFilesIn ../FASTQ_HardTrim/GRZ_F_Brain_c1_O_MIF1_1_val_1.fq.gz   ../FASTQ_HardTrim/GRZ_F_Brain_c1_O_MIF1_2_val_2.fq.gz  --outFilterScoreMinOverLread 0.4 --outFilterMatchNminOverLread 0.4 --readFilesCommand gzcat --runThreadN 1 --outFilterMultimapNmax 50 --outFilterIntronMotifs RemoveNoncanonicalUnannotated --outSAMtype BAM SortedByCoordinate  --alignEndsProtrude 15 ConcordantPair --outFileNamePrefix GRZ_F_Brain_c1_O_MIF_rep1_STAR_  
# STAR --genomeDir $KREF --readFilesIn ../FASTQ_HardTrim/GRZ_F_Brain_c1_O_MIF2_1_val_1.fq.gz   ../FASTQ_HardTrim/GRZ_F_Brain_c1_O_MIF2_2_val_2.fq.gz  --outFilterScoreMinOverLread 0.4 --outFilterMatchNminOverLread 0.4 --readFilesCommand gzcat --runThreadN 1 --outFilterMultimapNmax 50 --outFilterIntronMotifs RemoveNoncanonicalUnannotated --outSAMtype BAM SortedByCoordinate  --alignEndsProtrude 15 ConcordantPair --outFileNamePrefix GRZ_F_Brain_c1_O_MIF_rep2_STAR_  
# STAR --genomeDir $KREF --readFilesIn ../FASTQ_HardTrim/GRZ_F_Brain_c1_Y_CTL1_1_val_1.fq.gz   ../FASTQ_HardTrim/GRZ_F_Brain_c1_Y_CTL1_2_val_2.fq.gz  --outFilterScoreMinOverLread 0.4 --outFilterMatchNminOverLread 0.4 --readFilesCommand gzcat --runThreadN 1 --outFilterMultimapNmax 50 --outFilterIntronMotifs RemoveNoncanonicalUnannotated --outSAMtype BAM SortedByCoordinate  --alignEndsProtrude 15 ConcordantPair --outFileNamePrefix GRZ_F_Brain_c1_Y_CTL_rep1_STAR_  
# STAR --genomeDir $KREF --readFilesIn ../FASTQ_HardTrim/GRZ_F_Brain_c1_Y_CTL2_1_val_1.fq.gz   ../FASTQ_HardTrim/GRZ_F_Brain_c1_Y_CTL2_2_val_2.fq.gz  --outFilterScoreMinOverLread 0.4 --outFilterMatchNminOverLread 0.4 --readFilesCommand gzcat --runThreadN 1 --outFilterMultimapNmax 50 --outFilterIntronMotifs RemoveNoncanonicalUnannotated --outSAMtype BAM SortedByCoordinate  --alignEndsProtrude 15 ConcordantPair --outFileNamePrefix GRZ_F_Brain_c1_Y_CTL_rep2_STAR_  
# STAR --genomeDir $KREF --readFilesIn ../FASTQ_HardTrim/GRZ_F_Brain_c1_Y_CTL3_1_val_1.fq.gz   ../FASTQ_HardTrim/GRZ_F_Brain_c1_Y_CTL3_2_val_2.fq.gz  --outFilterScoreMinOverLread 0.4 --outFilterMatchNminOverLread 0.4 --readFilesCommand gzcat --runThreadN 1 --outFilterMultimapNmax 50 --outFilterIntronMotifs RemoveNoncanonicalUnannotated --outSAMtype BAM SortedByCoordinate  --alignEndsProtrude 15 ConcordantPair --outFileNamePrefix GRZ_F_Brain_c1_Y_CTL_rep3_STAR_  
# STAR --genomeDir $KREF --readFilesIn ../FASTQ_HardTrim/GRZ_M_Brain_c2_O_CTL1_1_val_1.fq.gz   ../FASTQ_HardTrim/GRZ_M_Brain_c2_O_CTL1_2_val_2.fq.gz  --outFilterScoreMinOverLread 0.4 --outFilterMatchNminOverLread 0.4 --readFilesCommand gzcat --runThreadN 1 --outFilterMultimapNmax 50 --outFilterIntronMotifs RemoveNoncanonicalUnannotated --outSAMtype BAM SortedByCoordinate  --alignEndsProtrude 15 ConcordantPair --outFileNamePrefix GRZ_M_Brain_c2_O_CTL_rep1_STAR_  
# STAR --genomeDir $KREF --readFilesIn ../FASTQ_HardTrim/GRZ_M_Brain_c2_O_CTL2_1_val_1.fq.gz   ../FASTQ_HardTrim/GRZ_M_Brain_c2_O_CTL2_2_val_2.fq.gz  --outFilterScoreMinOverLread 0.4 --outFilterMatchNminOverLread 0.4 --readFilesCommand gzcat --runThreadN 1 --outFilterMultimapNmax 50 --outFilterIntronMotifs RemoveNoncanonicalUnannotated --outSAMtype BAM SortedByCoordinate  --alignEndsProtrude 15 ConcordantPair --outFileNamePrefix GRZ_M_Brain_c2_O_CTL_rep2_STAR_  
# STAR --genomeDir $KREF --readFilesIn ../FASTQ_HardTrim/GRZ_M_Brain_c2_O_CTL3_1_val_1.fq.gz   ../FASTQ_HardTrim/GRZ_M_Brain_c2_O_CTL3_2_val_2.fq.gz  --outFilterScoreMinOverLread 0.4 --outFilterMatchNminOverLread 0.4 --readFilesCommand gzcat --runThreadN 1 --outFilterMultimapNmax 50 --outFilterIntronMotifs RemoveNoncanonicalUnannotated --outSAMtype BAM SortedByCoordinate  --alignEndsProtrude 15 ConcordantPair --outFileNamePrefix GRZ_M_Brain_c2_O_CTL_rep3_STAR_  
# STAR --genomeDir $KREF --readFilesIn ../FASTQ_HardTrim/GRZ_M_Brain_c2_O_MIF1_1_val_1.fq.gz   ../FASTQ_HardTrim/GRZ_M_Brain_c2_O_MIF1_2_val_2.fq.gz  --outFilterScoreMinOverLread 0.4 --outFilterMatchNminOverLread 0.4 --readFilesCommand gzcat --runThreadN 1 --outFilterMultimapNmax 50 --outFilterIntronMotifs RemoveNoncanonicalUnannotated --outSAMtype BAM SortedByCoordinate  --alignEndsProtrude 15 ConcordantPair --outFileNamePrefix GRZ_M_Brain_c2_O_MIF_rep1_STAR_  
# STAR --genomeDir $KREF --readFilesIn ../FASTQ_HardTrim/GRZ_M_Brain_c2_O_MIF2_1_val_1.fq.gz   ../FASTQ_HardTrim/GRZ_M_Brain_c2_O_MIF2_2_val_2.fq.gz  --outFilterScoreMinOverLread 0.4 --outFilterMatchNminOverLread 0.4 --readFilesCommand gzcat --runThreadN 1 --outFilterMultimapNmax 50 --outFilterIntronMotifs RemoveNoncanonicalUnannotated --outSAMtype BAM SortedByCoordinate  --alignEndsProtrude 15 ConcordantPair --outFileNamePrefix GRZ_M_Brain_c2_O_MIF_rep2_STAR_  
# STAR --genomeDir $KREF --readFilesIn ../FASTQ_HardTrim/GRZ_M_Brain_c2_O_MIF3_1_val_1.fq.gz   ../FASTQ_HardTrim/GRZ_M_Brain_c2_O_MIF3_2_val_2.fq.gz  --outFilterScoreMinOverLread 0.4 --outFilterMatchNminOverLread 0.4 --readFilesCommand gzcat --runThreadN 1 --outFilterMultimapNmax 50 --outFilterIntronMotifs RemoveNoncanonicalUnannotated --outSAMtype BAM SortedByCoordinate  --alignEndsProtrude 15 ConcordantPair --outFileNamePrefix GRZ_M_Brain_c2_O_MIF_rep3_STAR_  
# STAR --genomeDir $KREF --readFilesIn ../FASTQ_HardTrim/GRZ_M_Brain_c2_Y_CTL1_1_val_1.fq.gz   ../FASTQ_HardTrim/GRZ_M_Brain_c2_Y_CTL1_2_val_2.fq.gz  --outFilterScoreMinOverLread 0.4 --outFilterMatchNminOverLread 0.4 --readFilesCommand gzcat --runThreadN 1 --outFilterMultimapNmax 50 --outFilterIntronMotifs RemoveNoncanonicalUnannotated --outSAMtype BAM SortedByCoordinate  --alignEndsProtrude 15 ConcordantPair --outFileNamePrefix GRZ_M_Brain_c2_Y_CTL_rep1_STAR_  
# STAR --genomeDir $KREF --readFilesIn ../FASTQ_HardTrim/GRZ_M_Brain_c2_Y_CTL2_1_val_1.fq.gz   ../FASTQ_HardTrim/GRZ_M_Brain_c2_Y_CTL2_2_val_2.fq.gz  --outFilterScoreMinOverLread 0.4 --outFilterMatchNminOverLread 0.4 --readFilesCommand gzcat --runThreadN 1 --outFilterMultimapNmax 50 --outFilterIntronMotifs RemoveNoncanonicalUnannotated --outSAMtype BAM SortedByCoordinate  --alignEndsProtrude 15 ConcordantPair --outFileNamePrefix GRZ_M_Brain_c2_Y_CTL_rep2_STAR_  
# STAR --genomeDir $KREF --readFilesIn ../FASTQ_HardTrim/GRZ_M_Brain_c2_Y_CTL3_1_val_1.fq.gz   ../FASTQ_HardTrim/GRZ_M_Brain_c2_Y_CTL3_2_val_2.fq.gz  --outFilterScoreMinOverLread 0.4 --outFilterMatchNminOverLread 0.4 --readFilesCommand gzcat --runThreadN 1 --outFilterMultimapNmax 50 --outFilterIntronMotifs RemoveNoncanonicalUnannotated --outSAMtype BAM SortedByCoordinate  --alignEndsProtrude 15 ConcordantPair --outFileNamePrefix GRZ_M_Brain_c2_Y_CTL_rep3_STAR_  
# STAR --genomeDir $KREF --readFilesIn ../FASTQ_HardTrim/GRZ_M_Brain_c2_Y_CTL4_1_val_1.fq.gz   ../FASTQ_HardTrim/GRZ_M_Brain_c2_Y_CTL4_2_val_2.fq.gz  --outFilterScoreMinOverLread 0.4 --outFilterMatchNminOverLread 0.4 --readFilesCommand gzcat --runThreadN 1 --outFilterMultimapNmax 50 --outFilterIntronMotifs RemoveNoncanonicalUnannotated --outSAMtype BAM SortedByCoordinate  --alignEndsProtrude 15 ConcordantPair --outFileNamePrefix GRZ_M_Brain_c2_Y_CTL_rep4_STAR_  


# count over genes/TE (include fractional counts for multimappers: -M --fraction)
featureCounts -t exon -D 1500 -p -M --fraction -T 3 -s 0 -a 2021-12-02_GCF_001465895.1_MASKED_withFishTEDB_NR.gtf -o 2025-07-15_Killifish_Brain_Aging_GRZ_Females_Mif_RNAseq_counts.txt \
     GRZ_F_Brain_c1_Y_CTL_rep1_STAR_Aligned.sortedByCoord.out.bam  \
     GRZ_F_Brain_c1_Y_CTL_rep2_STAR_Aligned.sortedByCoord.out.bam  \
     GRZ_F_Brain_c1_Y_CTL_rep3_STAR_Aligned.sortedByCoord.out.bam  \
     GRZ_F_Brain_c1_O_CTL_rep1_STAR_Aligned.sortedByCoord.out.bam  \
     GRZ_F_Brain_c1_O_CTL_rep2_STAR_Aligned.sortedByCoord.out.bam  \
     GRZ_F_Brain_c1_O_CTL_rep3_STAR_Aligned.sortedByCoord.out.bam  \
     GRZ_F_Brain_c1_O_MIF_rep1_STAR_Aligned.sortedByCoord.out.bam  \
     GRZ_F_Brain_c1_O_MIF_rep2_STAR_Aligned.sortedByCoord.out.bam
     

featureCounts -t exon -D 1500 -p -M --fraction -T 3 -s 0 -a 2021-12-02_GCF_001465895.1_MASKED_withFishTEDB_NR.gtf -o 2025-07-15_Killifish_Brain_Aging_GRZ_Males_Mif_RNAseq_counts.txt \
     GRZ_M_Brain_c2_Y_CTL_rep1_STAR_Aligned.sortedByCoord.out.bam  \
     GRZ_M_Brain_c2_Y_CTL_rep2_STAR_Aligned.sortedByCoord.out.bam  \
     GRZ_M_Brain_c2_Y_CTL_rep3_STAR_Aligned.sortedByCoord.out.bam  \
     GRZ_M_Brain_c2_Y_CTL_rep4_STAR_Aligned.sortedByCoord.out.bam  \
     GRZ_M_Brain_c2_O_CTL_rep1_STAR_Aligned.sortedByCoord.out.bam  \
     GRZ_M_Brain_c2_O_CTL_rep2_STAR_Aligned.sortedByCoord.out.bam  \
     GRZ_M_Brain_c2_O_CTL_rep3_STAR_Aligned.sortedByCoord.out.bam  \
     GRZ_M_Brain_c2_O_MIF_rep1_STAR_Aligned.sortedByCoord.out.bam  \
     GRZ_M_Brain_c2_O_MIF_rep2_STAR_Aligned.sortedByCoord.out.bam  \
     GRZ_M_Brain_c2_O_MIF_rep3_STAR_Aligned.sortedByCoord.out.bam  
     
     
     