export GENIN="/Users/benayoun/Softwares/STAR-2.7.7a/genomes/MM39"


STAR --genomeDir $GENIN --readFilesIn ../FASTQ/Cerebellum/Run1/Cereb_3m1_1st_run_ATCACG_R1.fastq.gz      ../FASTQ/Cerebellum/Run1/Cereb_3m1_1st_run_ATCACG_R2.fastq.gz    --outFilterScoreMinOverLread 0.4 --outFilterMatchNminOverLread 0.4 --readFilesCommand gzcat --runThreadN 1 --outFilterMultimapNmax 50 --outFilterIntronMotifs RemoveNoncanonicalUnannotated --outSAMtype BAM SortedByCoordinate  --alignEndsProtrude 15 ConcordantPair --outFileNamePrefix Cereb_3m1_1st_RNAseq_STAR_      
STAR --genomeDir $GENIN --readFilesIn ../FASTQ/Cerebellum/Run1/Cereb_3m2_1st_run_CGATGT_R1.fastq.gz      ../FASTQ/Cerebellum/Run1/Cereb_3m2_1st_run_CGATGT_R2.fastq.gz    --outFilterScoreMinOverLread 0.4 --outFilterMatchNminOverLread 0.4 --readFilesCommand gzcat --runThreadN 1 --outFilterMultimapNmax 50 --outFilterIntronMotifs RemoveNoncanonicalUnannotated --outSAMtype BAM SortedByCoordinate  --alignEndsProtrude 15 ConcordantPair --outFileNamePrefix Cereb_3m2_1st_RNAseq_STAR_      
STAR --genomeDir $GENIN --readFilesIn ../FASTQ/Cerebellum/Run1/Cereb_3m3_1st_run_TTAGGC_R1.fastq.gz      ../FASTQ/Cerebellum/Run1/Cereb_3m3_1st_run_TTAGGC_R2.fastq.gz    --outFilterScoreMinOverLread 0.4 --outFilterMatchNminOverLread 0.4 --readFilesCommand gzcat --runThreadN 1 --outFilterMultimapNmax 50 --outFilterIntronMotifs RemoveNoncanonicalUnannotated --outSAMtype BAM SortedByCoordinate  --alignEndsProtrude 15 ConcordantPair --outFileNamePrefix Cereb_3m3_1st_RNAseq_STAR_      
STAR --genomeDir $GENIN --readFilesIn ../FASTQ/Cerebellum/Run1/Cereb_12m1_1st_run_TGACCA_R1.fastq.gz     ../FASTQ/Cerebellum/Run1/Cereb_12m1_1st_run_TGACCA_R2.fastq.gz   --outFilterScoreMinOverLread 0.4 --outFilterMatchNminOverLread 0.4 --readFilesCommand gzcat --runThreadN 1 --outFilterMultimapNmax 50 --outFilterIntronMotifs RemoveNoncanonicalUnannotated --outSAMtype BAM SortedByCoordinate  --alignEndsProtrude 15 ConcordantPair --outFileNamePrefix Cereb_12m1_1st_RNAseq_STAR_       
STAR --genomeDir $GENIN --readFilesIn ../FASTQ/Cerebellum/Run1/Cereb_12m2_1st_run_ACAGTG_R1.fastq.gz     ../FASTQ/Cerebellum/Run1/Cereb_12m2_1st_run_ACAGTG_R2.fastq.gz   --outFilterScoreMinOverLread 0.4 --outFilterMatchNminOverLread 0.4 --readFilesCommand gzcat --runThreadN 1 --outFilterMultimapNmax 50 --outFilterIntronMotifs RemoveNoncanonicalUnannotated --outSAMtype BAM SortedByCoordinate  --alignEndsProtrude 15 ConcordantPair --outFileNamePrefix Cereb_12m2_1st_RNAseq_STAR_       
STAR --genomeDir $GENIN --readFilesIn ../FASTQ/Cerebellum/Run1/Cereb_12m3_1st_run_GCCAAT_R1.fastq.gz     ../FASTQ/Cerebellum/Run1/Cereb_12m3_1st_run_GCCAAT_R2.fastq.gz   --outFilterScoreMinOverLread 0.4 --outFilterMatchNminOverLread 0.4 --readFilesCommand gzcat --runThreadN 1 --outFilterMultimapNmax 50 --outFilterIntronMotifs RemoveNoncanonicalUnannotated --outSAMtype BAM SortedByCoordinate  --alignEndsProtrude 15 ConcordantPair --outFileNamePrefix Cereb_12m3_1st_RNAseq_STAR_       
STAR --genomeDir $GENIN --readFilesIn ../FASTQ/Cerebellum/Run1/Cereb_29m2_1st_run_CAGATC_R1.fastq.gz     ../FASTQ/Cerebellum/Run1/Cereb_29m2_1st_run_CAGATC_R2.fastq.gz   --outFilterScoreMinOverLread 0.4 --outFilterMatchNminOverLread 0.4 --readFilesCommand gzcat --runThreadN 1 --outFilterMultimapNmax 50 --outFilterIntronMotifs RemoveNoncanonicalUnannotated --outSAMtype BAM SortedByCoordinate  --alignEndsProtrude 15 ConcordantPair --outFileNamePrefix Cereb_29m2_1st_RNAseq_STAR_       
STAR --genomeDir $GENIN --readFilesIn ../FASTQ/Cerebellum/Run1/Cereb_29m3_1st_run_ACTTGA_R1.fastq.gz     ../FASTQ/Cerebellum/Run1/Cereb_29m3_1st_run_ACTTGA_R2.fastq.gz   --outFilterScoreMinOverLread 0.4 --outFilterMatchNminOverLread 0.4 --readFilesCommand gzcat --runThreadN 1 --outFilterMultimapNmax 50 --outFilterIntronMotifs RemoveNoncanonicalUnannotated --outSAMtype BAM SortedByCoordinate  --alignEndsProtrude 15 ConcordantPair --outFileNamePrefix Cereb_29m3_1st_RNAseq_STAR_       
STAR --genomeDir $GENIN --readFilesIn ../FASTQ/Cerebellum/Run1/Cereb_29m4_1st_run_GATCAG_R1.fastq.gz     ../FASTQ/Cerebellum/Run1/Cereb_29m4_1st_run_GATCAG_R2.fastq.gz   --outFilterScoreMinOverLread 0.4 --outFilterMatchNminOverLread 0.4 --readFilesCommand gzcat --runThreadN 1 --outFilterMultimapNmax 50 --outFilterIntronMotifs RemoveNoncanonicalUnannotated --outSAMtype BAM SortedByCoordinate  --alignEndsProtrude 15 ConcordantPair --outFileNamePrefix Cereb_29m4_1st_RNAseq_STAR_       
STAR --genomeDir $GENIN --readFilesIn ../FASTQ/Cerebellum/Run2/Cereb_3m1_2nd_run_ATCACG_R1.fastq.gz      ../FASTQ/Cerebellum/Run2/Cereb_3m1_2nd_run_ATCACG_R2.fastq.gz    --outFilterScoreMinOverLread 0.4 --outFilterMatchNminOverLread 0.4 --readFilesCommand gzcat --runThreadN 1 --outFilterMultimapNmax 50 --outFilterIntronMotifs RemoveNoncanonicalUnannotated --outSAMtype BAM SortedByCoordinate  --alignEndsProtrude 15 ConcordantPair --outFileNamePrefix Cereb_3m1_2nd_RNAseq_STAR_      
STAR --genomeDir $GENIN --readFilesIn ../FASTQ/Cerebellum/Run2/Cereb_3m2_2nd_run_CGATGT_R1.fastq.gz      ../FASTQ/Cerebellum/Run2/Cereb_3m2_2nd_run_CGATGT_R2.fastq.gz    --outFilterScoreMinOverLread 0.4 --outFilterMatchNminOverLread 0.4 --readFilesCommand gzcat --runThreadN 1 --outFilterMultimapNmax 50 --outFilterIntronMotifs RemoveNoncanonicalUnannotated --outSAMtype BAM SortedByCoordinate  --alignEndsProtrude 15 ConcordantPair --outFileNamePrefix Cereb_3m2_2nd_RNAseq_STAR_      
STAR --genomeDir $GENIN --readFilesIn ../FASTQ/Cerebellum/Run2/Cereb_3m3_2nd_run_TTAGGC_R1.fastq.gz      ../FASTQ/Cerebellum/Run2/Cereb_3m3_2nd_run_TTAGGC_R2.fastq.gz    --outFilterScoreMinOverLread 0.4 --outFilterMatchNminOverLread 0.4 --readFilesCommand gzcat --runThreadN 1 --outFilterMultimapNmax 50 --outFilterIntronMotifs RemoveNoncanonicalUnannotated --outSAMtype BAM SortedByCoordinate  --alignEndsProtrude 15 ConcordantPair --outFileNamePrefix Cereb_3m3_2nd_RNAseq_STAR_      
STAR --genomeDir $GENIN --readFilesIn ../FASTQ/Cerebellum/Run2/Cereb_12m1_2nd_run_TGACCA_R1.fastq.gz     ../FASTQ/Cerebellum/Run2/Cereb_12m1_2nd_run_TGACCA_R2.fastq.gz   --outFilterScoreMinOverLread 0.4 --outFilterMatchNminOverLread 0.4 --readFilesCommand gzcat --runThreadN 1 --outFilterMultimapNmax 50 --outFilterIntronMotifs RemoveNoncanonicalUnannotated --outSAMtype BAM SortedByCoordinate  --alignEndsProtrude 15 ConcordantPair --outFileNamePrefix Cereb_12m1_2nd_RNAseq_STAR_       
STAR --genomeDir $GENIN --readFilesIn ../FASTQ/Cerebellum/Run2/Cereb_12m2_2nd_run_ACAGTG_R1.fastq.gz     ../FASTQ/Cerebellum/Run2/Cereb_12m2_2nd_run_ACAGTG_R2.fastq.gz   --outFilterScoreMinOverLread 0.4 --outFilterMatchNminOverLread 0.4 --readFilesCommand gzcat --runThreadN 1 --outFilterMultimapNmax 50 --outFilterIntronMotifs RemoveNoncanonicalUnannotated --outSAMtype BAM SortedByCoordinate  --alignEndsProtrude 15 ConcordantPair --outFileNamePrefix Cereb_12m2_2nd_RNAseq_STAR_       
STAR --genomeDir $GENIN --readFilesIn ../FASTQ/Cerebellum/Run2/Cereb_12m3_2nd_run_GCCAAT_R1.fastq.gz     ../FASTQ/Cerebellum/Run2/Cereb_12m3_2nd_run_GCCAAT_R2.fastq.gz   --outFilterScoreMinOverLread 0.4 --outFilterMatchNminOverLread 0.4 --readFilesCommand gzcat --runThreadN 1 --outFilterMultimapNmax 50 --outFilterIntronMotifs RemoveNoncanonicalUnannotated --outSAMtype BAM SortedByCoordinate  --alignEndsProtrude 15 ConcordantPair --outFileNamePrefix Cereb_12m3_2nd_RNAseq_STAR_       
STAR --genomeDir $GENIN --readFilesIn ../FASTQ/Cerebellum/Run2/Cereb_29m2_2nd_run_CAGATC_R1.fastq.gz     ../FASTQ/Cerebellum/Run2/Cereb_29m2_2nd_run_CAGATC_R2.fastq.gz   --outFilterScoreMinOverLread 0.4 --outFilterMatchNminOverLread 0.4 --readFilesCommand gzcat --runThreadN 1 --outFilterMultimapNmax 50 --outFilterIntronMotifs RemoveNoncanonicalUnannotated --outSAMtype BAM SortedByCoordinate  --alignEndsProtrude 15 ConcordantPair --outFileNamePrefix Cereb_29m2_2nd_RNAseq_STAR_       
STAR --genomeDir $GENIN --readFilesIn ../FASTQ/Cerebellum/Run2/Cereb_29m3_2nd_run_ACTTGA_R1.fastq.gz     ../FASTQ/Cerebellum/Run2/Cereb_29m3_2nd_run_ACTTGA_R2.fastq.gz   --outFilterScoreMinOverLread 0.4 --outFilterMatchNminOverLread 0.4 --readFilesCommand gzcat --runThreadN 1 --outFilterMultimapNmax 50 --outFilterIntronMotifs RemoveNoncanonicalUnannotated --outSAMtype BAM SortedByCoordinate  --alignEndsProtrude 15 ConcordantPair --outFileNamePrefix Cereb_29m3_2nd_RNAseq_STAR_       
STAR --genomeDir $GENIN --readFilesIn ../FASTQ/Cerebellum/Run2/Cereb_29m4_2nd_run_GATCAG_R1.fastq.gz     ../FASTQ/Cerebellum/Run2/Cereb_29m4_2nd_run_GATCAG_R2.fastq.gz   --outFilterScoreMinOverLread 0.4 --outFilterMatchNminOverLread 0.4 --readFilesCommand gzcat --runThreadN 1 --outFilterMultimapNmax 50 --outFilterIntronMotifs RemoveNoncanonicalUnannotated --outSAMtype BAM SortedByCoordinate  --alignEndsProtrude 15 ConcordantPair --outFileNamePrefix Cereb_29m4_2nd_RNAseq_STAR_       
STAR --genomeDir $GENIN --readFilesIn ../FASTQ/NPCs/NPC_3m5-CGATGT_R1.fastq.gz                           ../FASTQ/NPCs/NPC_3m5-CGATGT_R2.fastq.gz                         --outFilterScoreMinOverLread 0.4 --outFilterMatchNminOverLread 0.4 --readFilesCommand gzcat --runThreadN 1 --outFilterMultimapNmax 50 --outFilterIntronMotifs RemoveNoncanonicalUnannotated --outSAMtype BAM SortedByCoordinate  --alignEndsProtrude 15 ConcordantPair --outFileNamePrefix NPC_3m5_RNAseq_STAR_   
STAR --genomeDir $GENIN --readFilesIn ../FASTQ/NPCs/NPC_3m6-TGACCA_R1.fastq.gz                           ../FASTQ/NPCs/NPC_3m6-TGACCA_R2.fastq.gz                         --outFilterScoreMinOverLread 0.4 --outFilterMatchNminOverLread 0.4 --readFilesCommand gzcat --runThreadN 1 --outFilterMultimapNmax 50 --outFilterIntronMotifs RemoveNoncanonicalUnannotated --outSAMtype BAM SortedByCoordinate  --alignEndsProtrude 15 ConcordantPair --outFileNamePrefix NPC_3m6_RNAseq_STAR_   
STAR --genomeDir $GENIN --readFilesIn ../FASTQ/NPCs/NPC_12m5-ACAGTG_R1.fastq.gz                          ../FASTQ/NPCs/NPC_12m5-ACAGTG_R2.fastq.gz                        --outFilterScoreMinOverLread 0.4 --outFilterMatchNminOverLread 0.4 --readFilesCommand gzcat --runThreadN 1 --outFilterMultimapNmax 50 --outFilterIntronMotifs RemoveNoncanonicalUnannotated --outSAMtype BAM SortedByCoordinate  --alignEndsProtrude 15 ConcordantPair --outFileNamePrefix NPC_12m5_RNAseq_STAR_   
STAR --genomeDir $GENIN --readFilesIn ../FASTQ/NPCs/NPC_12m6-GCCAAT_R1.fastq.gz                          ../FASTQ/NPCs/NPC_12m6-GCCAAT_R2.fastq.gz                        --outFilterScoreMinOverLread 0.4 --outFilterMatchNminOverLread 0.4 --readFilesCommand gzcat --runThreadN 1 --outFilterMultimapNmax 50 --outFilterIntronMotifs RemoveNoncanonicalUnannotated --outSAMtype BAM SortedByCoordinate  --alignEndsProtrude 15 ConcordantPair --outFileNamePrefix NPC_12m6_RNAseq_STAR_   
STAR --genomeDir $GENIN --readFilesIn ../FASTQ/NPCs/NPC_29m5-CAGATC_R1.fastq.gz                          ../FASTQ/NPCs/NPC_29m5-CAGATC_R2.fastq.gz                        --outFilterScoreMinOverLread 0.4 --outFilterMatchNminOverLread 0.4 --readFilesCommand gzcat --runThreadN 1 --outFilterMultimapNmax 50 --outFilterIntronMotifs RemoveNoncanonicalUnannotated --outSAMtype BAM SortedByCoordinate  --alignEndsProtrude 15 ConcordantPair --outFileNamePrefix NPC_29m5_RNAseq_STAR_   
STAR --genomeDir $GENIN --readFilesIn ../FASTQ/NPCs/NPC_29m6-CTTGTA_R1.fastq.gz                          ../FASTQ/NPCs/NPC_29m6-CTTGTA_R2.fastq.gz                        --outFilterScoreMinOverLread 0.4 --outFilterMatchNminOverLread 0.4 --readFilesCommand gzcat --runThreadN 1 --outFilterMultimapNmax 50 --outFilterIntronMotifs RemoveNoncanonicalUnannotated --outSAMtype BAM SortedByCoordinate  --alignEndsProtrude 15 ConcordantPair --outFileNamePrefix NPC_29m6_RNAseq_STAR_   
STAR --genomeDir $GENIN --readFilesIn ../FASTQ/OB/OB_3m1_ATCACG_R1.fastq.gz                              ../FASTQ/OB/OB_3m1_ATCACG_R2.fastq.gz                            --outFilterScoreMinOverLread 0.4 --outFilterMatchNminOverLread 0.4 --readFilesCommand gzcat --runThreadN 1 --outFilterMultimapNmax 50 --outFilterIntronMotifs RemoveNoncanonicalUnannotated --outSAMtype BAM SortedByCoordinate  --alignEndsProtrude 15 ConcordantPair --outFileNamePrefix OB_3m1_RNAseq_STAR_   
STAR --genomeDir $GENIN --readFilesIn ../FASTQ/OB/OB_3m2_CGATGT_R1.fastq.gz                              ../FASTQ/OB/OB_3m2_CGATGT_R2.fastq.gz                            --outFilterScoreMinOverLread 0.4 --outFilterMatchNminOverLread 0.4 --readFilesCommand gzcat --runThreadN 1 --outFilterMultimapNmax 50 --outFilterIntronMotifs RemoveNoncanonicalUnannotated --outSAMtype BAM SortedByCoordinate  --alignEndsProtrude 15 ConcordantPair --outFileNamePrefix OB_3m2_RNAseq_STAR_   
STAR --genomeDir $GENIN --readFilesIn ../FASTQ/OB/OB_3m3_TTAGGC_R1.fastq.gz                              ../FASTQ/OB/OB_3m3_TTAGGC_R2.fastq.gz                            --outFilterScoreMinOverLread 0.4 --outFilterMatchNminOverLread 0.4 --readFilesCommand gzcat --runThreadN 1 --outFilterMultimapNmax 50 --outFilterIntronMotifs RemoveNoncanonicalUnannotated --outSAMtype BAM SortedByCoordinate  --alignEndsProtrude 15 ConcordantPair --outFileNamePrefix OB_3m3_RNAseq_STAR_   
STAR --genomeDir $GENIN --readFilesIn ../FASTQ/OB/OB_12m1_TGACCA_R1.fastq.gz                             ../FASTQ/OB/OB_12m1_TGACCA_R2.fastq.gz                           --outFilterScoreMinOverLread 0.4 --outFilterMatchNminOverLread 0.4 --readFilesCommand gzcat --runThreadN 1 --outFilterMultimapNmax 50 --outFilterIntronMotifs RemoveNoncanonicalUnannotated --outSAMtype BAM SortedByCoordinate  --alignEndsProtrude 15 ConcordantPair --outFileNamePrefix OB_12m1_RNAseq_STAR_   
STAR --genomeDir $GENIN --readFilesIn ../FASTQ/OB/OB_12m3_GCCAAT_R1.fastq.gz                             ../FASTQ/OB/OB_12m3_GCCAAT_R2.fastq.gz                           --outFilterScoreMinOverLread 0.4 --outFilterMatchNminOverLread 0.4 --readFilesCommand gzcat --runThreadN 1 --outFilterMultimapNmax 50 --outFilterIntronMotifs RemoveNoncanonicalUnannotated --outSAMtype BAM SortedByCoordinate  --alignEndsProtrude 15 ConcordantPair --outFileNamePrefix OB_12m3_RNAseq_STAR_   
STAR --genomeDir $GENIN --readFilesIn ../FASTQ/OB/OB_29m2_CAGATC_R1.fastq.gz                             ../FASTQ/OB/OB_29m2_CAGATC_R2.fastq.gz                           --outFilterScoreMinOverLread 0.4 --outFilterMatchNminOverLread 0.4 --readFilesCommand gzcat --runThreadN 1 --outFilterMultimapNmax 50 --outFilterIntronMotifs RemoveNoncanonicalUnannotated --outSAMtype BAM SortedByCoordinate  --alignEndsProtrude 15 ConcordantPair --outFileNamePrefix OB_29m2_RNAseq_STAR_   
STAR --genomeDir $GENIN --readFilesIn ../FASTQ/OB/OB_29m3_ACTTGA_R1.fastq.gz                             ../FASTQ/OB/OB_29m3_ACTTGA_R2.fastq.gz                           --outFilterScoreMinOverLread 0.4 --outFilterMatchNminOverLread 0.4 --readFilesCommand gzcat --runThreadN 1 --outFilterMultimapNmax 50 --outFilterIntronMotifs RemoveNoncanonicalUnannotated --outSAMtype BAM SortedByCoordinate  --alignEndsProtrude 15 ConcordantPair --outFileNamePrefix OB_29m3_RNAseq_STAR_   
STAR --genomeDir $GENIN --readFilesIn ../FASTQ/OB/OB_29m4_GATCAG_R1.fastq.gz                             ../FASTQ/OB/OB_29m4_GATCAG_R2.fastq.gz                           --outFilterScoreMinOverLread 0.4 --outFilterMatchNminOverLread 0.4 --readFilesCommand gzcat --runThreadN 1 --outFilterMultimapNmax 50 --outFilterIntronMotifs RemoveNoncanonicalUnannotated --outSAMtype BAM SortedByCoordinate  --alignEndsProtrude 15 ConcordantPair --outFileNamePrefix OB_29m4_RNAseq_STAR_   


samtools merge Cereb_3m1_RNAseq_STAR_Aligned.MERGED.bam  Cereb_3m1_1st_RNAseq_STAR_Aligned.sortedByCoord.out.bam  Cereb_3m1_2nd_RNAseq_STAR_Aligned.sortedByCoord.out.bam  
samtools merge Cereb_3m2_RNAseq_STAR_Aligned.MERGED.bam  Cereb_3m2_1st_RNAseq_STAR_Aligned.sortedByCoord.out.bam  Cereb_3m2_2nd_RNAseq_STAR_Aligned.sortedByCoord.out.bam  
samtools merge Cereb_3m3_RNAseq_STAR_Aligned.MERGED.bam  Cereb_3m3_1st_RNAseq_STAR_Aligned.sortedByCoord.out.bam  Cereb_3m3_2nd_RNAseq_STAR_Aligned.sortedByCoord.out.bam  
samtools merge Cereb_12m1_RNAseq_STAR_Aligned.MERGED.bam Cereb_12m1_1st_RNAseq_STAR_Aligned.sortedByCoord.out.bam Cereb_12m1_2nd_RNAseq_STAR_Aligned.sortedByCoord.out.bam
samtools merge Cereb_12m2_RNAseq_STAR_Aligned.MERGED.bam Cereb_12m2_1st_RNAseq_STAR_Aligned.sortedByCoord.out.bam Cereb_12m2_2nd_RNAseq_STAR_Aligned.sortedByCoord.out.bam
samtools merge Cereb_12m3_RNAseq_STAR_Aligned.MERGED.bam Cereb_12m3_1st_RNAseq_STAR_Aligned.sortedByCoord.out.bam Cereb_12m3_2nd_RNAseq_STAR_Aligned.sortedByCoord.out.bam
samtools merge Cereb_29m2_RNAseq_STAR_Aligned.MERGED.bam Cereb_29m2_1st_RNAseq_STAR_Aligned.sortedByCoord.out.bam Cereb_29m2_2nd_RNAseq_STAR_Aligned.sortedByCoord.out.bam
samtools merge Cereb_29m3_RNAseq_STAR_Aligned.MERGED.bam Cereb_29m3_1st_RNAseq_STAR_Aligned.sortedByCoord.out.bam Cereb_29m3_2nd_RNAseq_STAR_Aligned.sortedByCoord.out.bam
samtools merge Cereb_29m4_RNAseq_STAR_Aligned.MERGED.bam Cereb_29m4_1st_RNAseq_STAR_Aligned.sortedByCoord.out.bam Cereb_29m4_2nd_RNAseq_STAR_Aligned.sortedByCoord.out.bam


featureCounts -t exon -D 1500 -p --primary -T 1 -s 0 -a /Users/benayoun/Softwares/Genomes/mm39_refGene.gtf -o 2025-08-02_Benayoun_NSPCs_Aging_counts_MM39.txt \
 	NPC_3m5_RNAseq_STAR_Aligned.sortedByCoord.out.bam   \
 	NPC_3m6_RNAseq_STAR_Aligned.sortedByCoord.out.bam   \
 	NPC_12m5_RNAseq_STAR_Aligned.sortedByCoord.out.bam   \
 	NPC_12m6_RNAseq_STAR_Aligned.sortedByCoord.out.bam    \
 	NPC_29m5_RNAseq_STAR_Aligned.sortedByCoord.out.bam    \
 	NPC_29m6_RNAseq_STAR_Aligned.sortedByCoord.out.bam    

featureCounts -t exon -D 1500 -p --primary -T 1 -s 0 -a /Users/benayoun/Softwares/Genomes/mm39_refGene.gtf -o 2025-08-02_Benayoun_OB_Aging_counts_MM39.txt \
 	OB_3m1_RNAseq_STAR_Aligned.sortedByCoord.out.bam \
 	OB_3m2_RNAseq_STAR_Aligned.sortedByCoord.out.bam \
 	OB_3m3_RNAseq_STAR_Aligned.sortedByCoord.out.bam \
 	OB_12m1_RNAseq_STAR_Aligned.sortedByCoord.out.bam \
 	OB_12m3_RNAseq_STAR_Aligned.sortedByCoord.out.bam \
 	OB_29m2_RNAseq_STAR_Aligned.sortedByCoord.out.bam \
 	OB_29m3_RNAseq_STAR_Aligned.sortedByCoord.out.bam \
 	OB_29m4_RNAseq_STAR_Aligned.sortedByCoord.out.bam


featureCounts -t exon -D 1500 -p --primary -T 1 -s 0 -a /Users/benayoun/Softwares/Genomes/mm39_refGene.gtf -o 2025-08-02_Benayoun_Cerebellum_Aging_counts_MM39.txt \
 	Cereb_3m1_RNAseq_STAR_Aligned.MERGED.bam  \
 	Cereb_3m2_RNAseq_STAR_Aligned.MERGED.bam  \
 	Cereb_3m3_RNAseq_STAR_Aligned.MERGED.bam  \
 	Cereb_12m1_RNAseq_STAR_Aligned.MERGED.bam \
 	Cereb_12m2_RNAseq_STAR_Aligned.MERGED.bam \
 	Cereb_12m3_RNAseq_STAR_Aligned.MERGED.bam \
 	Cereb_29m2_RNAseq_STAR_Aligned.MERGED.bam \
 	Cereb_29m3_RNAseq_STAR_Aligned.MERGED.bam \
 	Cereb_29m4_RNAseq_STAR_Aligned.MERGED.bam
